# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_article_article_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
    ]
